### PR TITLE
Expand broadNative runtime with nativeJit.

### LINKED ISSUE #1028: Include _onNativeJit in broadNative?
Include `_onNativeJit` in `broadNative`?
https://github.com/dart-lang/pana/blob/master/lib/src/tag/_specs.dart#L103-L108

Otherwise, we won't detect platforms tags for anything importing things like `dart:cli`, see:
https://pub.dev/packages/winmd/score

I think `_onNativeJit` shouldn't be part of `broadFlutter`, so we won't detect `sdk:flutter` when `dart:mirrors` is used.

### PR DESCRIPTION
**Pull request by isoos**
Fixes #1028.

### CODE REVIEW

**Review by sigurdm — APPROVED** [review]
LGTM

**Comment by sigurdm** [comment]
One can say it is surprising a package can get platform:android when it uses dart:mirrors. I don't think there is a way do deploy on android without flutter (where mirrors are not allowed)... but I'm not sure how important that is.

**Comment by isoos** [comment]
> One can say it is surprising a package can get platform:android when it uses dart:mirrors. I don't think there is a way do deploy on android without flutter (where mirrors are not allowed)... but I'm not sure how important that is.

I also think that this is strange, and I think it is a sign that we should do this differently.

**Comment by isoos** [comment]
Closing as this seems to get us unintended side effects.

**Pull request closed without merging**
