### PR TITLE
Only require flutter if package uses flutter

### PR DESCRIPTION
**Pull request by kentcb**
If a package is Dart-only, it should not receive a 10 point deduction when Flutter isn't installed, but that is currently what occurs. This PR fixes the logic in question.

### CODE REVIEW

**Review by isoos — APPROVED** [review]

**Comment by isoos** [comment]
Please fix formatting with dartfmt.

**Comment by kentcb** [comment]
@isoos Formatting is fixed, but CI seems to be failing e2e test due to difference in line ending even though my change shouldn't impact that...any thoughts?

**Comment by kentcb** [comment]
Ah, actually, it would make sense if the golden files include messages/output related to Flutter for non-Flutter packages because they would no longer be there. I'll take a look after work.

**Comment by isoos** [comment]
> Ah, actually, it would make sense if the golden files include messages/output related to Flutter for non-Flutter packages because they would no longer be there. I'll take a look after work.

Delete the files in the `test/goldens/end2end` directory and run test again. They will be failing, but regenerate the files with the current output, and it will be easy to compare the impact.

**Comment by kentcb** [comment]
Yeah, I tried that but it's not exactly Windows-friendly. i.e. generating a bunch of platform-specific junk. Am trying to fix somewhat manually...

**Comment by kentcb** [comment]
@isoos OK, good to go

**Review by isoos — APPROVED** [review]
Thanks, this looks great!

**Pull request merged**
