### PR TITLE
Use archiveUrl when specified.

### PR DESCRIPTION
**Pull request by isoos**
- #1165
- I also think we should not implement #1170, as it also relies on the potentially cached version list.

### CODE REVIEW

**Comment by sigurdm** [comment]
> I also think we should not implement Pana should use dart pub to download and extract packages.  #1170, as it also relies on the potentially cached version list.

Not sure this is true if I read it right. pub doesn't rely on the cached version listings - only as a heuristic to speed up requesting version listings for transitive dependencies.

**Review by sigurdm — APPROVED** [review]
LGTM

**Comment by sigurdm** [comment]
> Not sure this is true if I read it right. pub doesn't rely on the cached version listings - only as a heuristic to speed up requesting version listings for transitive dependencies.

Ah you were talking about the cached version listings on pub.dev - just forget what I wrote then.

**Comment by isoos** [comment]
> @isoos I don't understand this concern. The dart pub client will rely on the same APIs as the downloadPackage method uses.

Exactly, and that is causing analysis failures right now. This PR allows us to feed the `archiveUrl` to pana without going through the cached API response.

The root cause of this issue is the cache: we receive a new version, but the cache may be stale for 10 minutes (either because we have split traffic or failed to purge it), during which any analysis that uses the API will fail for the new version.

**Comment by sigurdm** [comment]
Could we make some retry-logic in pana (or perhaps pub-worker) to take these possible 10 minutes into account?

* pub get
  - (wait 1 minute)
* pub get
  - (wait 2 minutes)
* pub get
  - (wait 3 minutes)
* pub get
  - (wait 4 minutes)
* pub get
  - give up.

...or something even more clever

**Comment by isoos** [comment]
I don't think `pub get` should have any minute+ retry. A few seconds may be okay for transient issues, but the process shouldn't hang for minutes just because there may be a cache invalidation down the line...

Coming from that angle, maybe this change is not needed either, instead, we should have a better retry logic on pub.dev, e.g. invalidating the cache if the first attempt of a latest version fails. (And do the second attempt after the cache has been invalidated.)

**Comment by isoos** [comment]
Closing this as we will land the cache purge instead.

**Pull request closed without merging**
