### PR TITLE
Change `flutter packages` to `flutter pub`

### PR DESCRIPTION
**Pull request by mit-mit**
Related to flutter/flutter#33041

### CODE REVIEW

**Comment by isoos** [comment]
Do we also need to change the executed `flutter packages pub upgrade` -> `flutter pub pub upgrade` or will the `packages` work for a while?

**Comment by mit-mit** [comment]
> Do we also need to change the executed flutter packages pub upgrade -> flutter pub pub upgrade or will the packages work for a while?

`flutter packages` is still supported (it's technically now an alias for `flutter pub`).

But no reason not to shorten that to just `flutter pub upgrade`; will do that now.

**Comment by isoos** [comment]
Just checked: for the command execution we need to use `flutter pub pub upgrade`, because `flutter pub upgrade` does not output the package information (e.g. resolved and available versions).

**Comment by mit-mit** [comment]
Ah, I see, so we rely on the raw output from `pub`? Yes, then `flutter pub pub` is needed.

**Comment by mit-mit** [comment]
@isoos PTAL now

**Pull request merged**
