### PR TITLE
Move unconstrained version penalty from health score to maintenance.

### PR DESCRIPTION
**Pull request by isoos**
#222

### CODE REVIEW

**Comment by mit-mit** [comment]
cc @isoos looks like some tests are failing in CI?

**Comment by isoos** [comment]
Fix in progress.

I used to receive notifications when the CI failed, but not anymore. Do you happen to know where I need to set the appropriate checkbox to get notified?

**Comment by isoos** [comment]
Oh, the current CI issue seems to be coming from the upgrade of the SDK to the dev 17. It is generating a bit different analyzer output, which is unrelated to my change, I'll address it separately. Not sure why we don't control the version in the CI config.

**Comment by isoos** [comment]
CI cleared after we have pinned the Dart SDK version.

**Pull request merged**
