### PR TITLE
Handle MIT license without explicit 'MIT License' text.

### LINKED ISSUE #200: Failed to detect uuid's license.
@mit-mit originally reported: https://pub.dartlang.org/packages/uuid has an 'unknown' license. However, github is able to detect it as MIT: https://github.com/Daegalus/dart-uuid/blob/master/LICENSE

### PR DESCRIPTION
**Pull request by isoos**
Fixes #200

### CODE REVIEW

**Comment by mit-mit** [comment]
@kevmoo this one is also failing, can you see if that is the same issue:
https://github.com/brianegan/font_awesome_flutter/blob/master/LICENSE.md

Also, was this deployed?

**Comment by isoos** [comment]
This was not deployed yet.

**Comment by isoos** [comment]
> can you see if that is the same issue

Checked it manually, it will be detected once it is deployed.

**Comment by iamchathu** [comment]
@isoos 
https://pub.dev/packages/flutter_auth_provider still got detected as unknown

**Pull request merged**
