### PR TITLE
Remove deprecated `pub` usage in readme

### PR DESCRIPTION
**Pull request by shilangyu**
Also removed the leading `> ` as it only makes copying annoying

### CODE REVIEW

**Comment by shilangyu** [comment]
Signed the CLA

**Review by isoos — APPROVED** [review]

**Comment by isoos** [comment]
@shilangyu please take another look at the missing CLA

**Comment by shilangyu** [comment]
Can you rerun the CLA check? I signed it after opening the PR

**Comment by shilangyu** [comment]
Force pushed to re-trigger the run.

**Pull request merged**
