### PR TITLE
misc: prepare to release 0.11.9

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@sortie @isoos – ello?

**Comment by isoos** [comment]
While this in general looks good to me, I'm a bit hesitant to pull the trigger on this, because pub site is still running on dev.63.

**Comment by kevmoo** [comment]
> While this in general looks good to me, I'm a bit hesitant to pull the trigger on this, because pub site is still running on dev.63.

Ack.

**Comment by isoos** [comment]
@sortie: would you be able to merge and publish this new version? I'll need it for the pub SDK upgrade.

**Comment by kevmoo** [comment]
I did the merge. Happy to publish if @sortie is OOO for the day...

**Comment by isoos** [comment]
I think he is out now, could you please publish it @kevmoo?

**Comment by kevmoo** [comment]
Published!

**Comment by sortie** [comment]
Thanks Kevin!

**Pull request merged**
