### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by athomas**

### CODE REVIEW

**Comment by isoos** [comment]
It seems to be stuck somewhere:
````
Attempt:850 waiting for isolate vm-isolate to check in
Attempt:850 waiting for isolate dartdev to check in
````

**Comment by athomas** [comment]
> It seems to be stuck somewhere:
> 
> ```
> Attempt:850 waiting for isolate vm-isolate to check in
> Attempt:850 waiting for isolate dartdev to check in
> ```

Probably an issue with the dart verbs on this ancient version. I'll try to use a newer one and see what happens.

**Comment by athomas** [comment]
@isoos on 2.12.0-259.0.dev it works, but now 10 instead of 4 (on travis) tests are failing.

**Comment by isoos** [comment]
> 2.12.0-259.0.dev it works, but now 10 instead of 4 (on travis) tests are failing.

To update the end2end tests, you must delete the files in `test/goldens/end2end/*` and run `pub run test` with the new SDK. It will regenerate the golden files, and updating the PR should resolve the failing tests.

**Review by isoos — APPROVED** [review]

**Pull request merged**
