### PR TITLE
Default analysis options: ignore deprecated from same package.

### PR DESCRIPTION
**Pull request by isoos**
#1055

### CODE REVIEW

**Review by jonasfj — COMMENTED** [review]
I'm not sure we should take an opinion on this.

**Comment by jonasfj** [comment]
@mit-mit did you reach a conclusion after digging into diagnostics vs lints?

**Comment by mit-mit** [comment]
Not yet. This has evolved into a potentially very large restructuring of how we do this, so it's taking a little while.

But I'm very supportive of temporarily solving this by ignoring this in scoring.

**Review by jonasfj — APPROVED** [review]

**Comment by isoos** [comment]
As discussed today, not merging this for now.

**Pull request closed without merging**
